import { Metadata } from "next";
import { cookies } from "next/headers";
import React from "react";
import "@refinedev/antd/dist/reset.css";
import "@common/styles/global.css";
import { RefineLayout } from "@refine/RefineLayout";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value
    ? theme?.value === "dark"
      ? "dark"
      : "light"
    : "dark";

  return (
    <html lang="en">
      <body>
        <RefineLayout defaultMode={defaultMode}>{children}</RefineLayout>
      </body>
    </html>
  );
}
